---

- name: main | Create user account for Kibana
  user:
    name={{ kibana_user }}
    system=yes
    home={{ kibana_base_dir }}
    shell=/bin/false
    state=present

- name: main | Create directories for kibana
  file: 
    path="{{ item }}"
    state=directory
  with_items:
    - "{{kibana_base_dir}}"
    - "{{kibana_source_dir}}"
    - "{{kibana_instal_dir}}"

- name: main | Fetch kibana tar.gz
  get_url: 
    url="{{ kibana_url }}"
    dest="{{ kibana_source_dir }}/{{ kibana_tar }}"
  register: kibana_download

- name: main | untar kibana tar.gz
  unarchive: 
    src="{{kibana_source_dir}}/{{kibana_tar}}"
    dest="{{kibana_instal_dir}}"
    copy=no
  when: kibana_download | changed

- name: main | Create working link
  file: 
    src="{{ kibana_instal_dir }}/{{ kibana_dir }}"
    dest="{{ kibana_install_link }}"
    state=link
  when: kibana_download | changed

- name: main | Deploy kibana4 kibana.yml
  template:
    src=kibana.yml.j2
    dest={{ kibana_instal_dir }}/kibana-{{ kibana_version }}-{{ kibana_os }}-{{ kibana_arch }}/config/kibana.yml
  notify:
    - Restart Kibana


#- name: main | Deploy my dashboards
#  template:
#    src="{{item.src}}"
#    dest="{{kibana_dashboard_dir}}/{{item.name}}"
#  with_items: kibana_dashboards
#  when: kibana_dashboard_install

#
#
#- name: Configure Kibana service definition
#  template: src=kibana.conf.j2 dest=/etc/init/kibana.conf
#  notify:
#    - Restart Kibana
#
#- name: Touch log file if it does not exist
#  command: touch {{ kibana_log }}
#           creates={{ kibana_log }}
#
#- name: Set log file permissions
#  file: path={{ kibana_log }} owner=kibana group=kibana mode=0644
#
#- name: Configure Kibana log rotation
#  template: src=logrotate_kibana.j2 dest=/etc/logrotate.d/kibana